#!/bin/sh
# postrm script for consul-template

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
  purge)
    rm -rf /etc/consul-template.d
    rm -rf /usr/share/consul-template
  ;;

  upgrade)
    if initctl status consul-template | grep "start/running"; then
        initctl restart consul-template
    fi
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    exit 0
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0
